### ISSUE TITLE
Annotated graphics

### ISSUE THREAD

**Issue by neon5d** [neurodial/LibE2E#1]
Do you any information to derive annotated graphics on OCT images from e2e?
It looks like a 0x2730 type.
Thank you

**Comment by kaygcharite** [comment]
Hello neon5d

what do you mean with annotated graphics? I'm afraid we don't use that feature.

Best Kay

**Comment by neon5d** [comment]
Hello Kay,

We can overlay user graphics (circle or line like graphics) on the OCT images using the Heidelberg Eye Explorer.  Current libE2E seems to ignore this type. (I guessed the user graphics type is 0x2730)
My question was whether you have any information or plan to support user annotation.

Thank you,

**Comment by kaygcharite** [comment]
Hello neon5d,

I have asked some Lab members about the markers overlay annotation HEYEX. This feature is not used and I have no information or sample data about it.

If you give me information and simple data, I might be able to add support for it in LibE2E. Do you need this only in the library or also in LibOctData/OCT markers?

Best Kay

**Comment by neon5d** [comment]
Do you have any e2e data? I can add annotation and give it back to you.
I only need libe2e but need some examples on how to access data.

**Comment by kaygcharite** [comment]
Sorry, but I can't send you an E2E file. I also think that a file with sample data might not be enough and that it is difficult to interpret the data without viewing the data in HEYEX. To complicate matters, there are partially unitized areas in the E2E data, at least in my experience.

Do you have other information besides the 0x2730 identifier?

**Comment by neon5d** [comment]
Not too much.  My guess is It starts from RGB color information and coordinators of each pixel.  I hope you can access some software then, you might figure it out.

**Comment by kaygcharite** [comment]
Unfortunately I don't have access to the HEYEX software anymore because I am no longer a member of the working group and I'm afraid the project was not taken over by anyone.

**Comment by neon5d** [comment]
Thank for your all comments.
I hope some chances are available.
