### ISSUE TITLE
Extracting scan date

### ISSUE THREAD

**Issue by marksgraham** [neurodial/LibE2E#5]
Hi,

Thanks for your useful repo! I'm trying to extract scan date from .e2e. I'm struggling with the interpretation of the acquisitionTime here:
https://github.com/neurodial/LibE2E/blob/d26d2d9db64c5f765c0241ecc22177bb0c440c87/E2E/dataelements/bscanmetadataelement.cpp#L75
does this value contain date as well as time information? I'm struggling to see how the values I extract (e.g. 130129068663440000) can be related to a recognisable date and time.

Another option is to extract the study date from here: 
https://github.com/neurodial/LibE2E/blob/d26d2d9db64c5f765c0241ecc22177bb0c440c87/E2E/dataelements/studydata.cpp#L35
but once again I'm struggling to relate the values I extract to a recognisable date.

Thanks in advance for any help.
Mark

**Comment by kaygdev** [comment]
Hi Mark,

thank you for you feedback. The acquisitionTime is encoded in windows ticks (int64). It is converted in
https://github.com/neurodial/LibOctData/blob/6a6f667e8c9c740867c8eaa76b10e31845dccd38/octdata/import/he_e2e/he_e2eread.cpp#L388

The studyDate use the windows time format (double), it is converted in 
https://github.com/neurodial/LibOctData/blob/6a6f667e8c9c740867c8eaa76b10e31845dccd38/octdata/import/he_e2e/he_e2eread.cpp#L102

You can find the converting code in https://github.com/neurodial/LibOctData/blob/master/octdata/datastruct/date.cpp

For explaination, the LibE2E is like a frontend for LibOctData. It reads the E2E file and fills a structure that is close to the E2E format. In the LibOctData this structure is then evaluated and converted into a uniform format. The other programs then build on this (convert_oct_data, octdata4matlab, octdata4python, OCT-Marker).

Best
Kay

**Comment by marksgraham** [comment]
Thanks for this - really helpful!
